# Generated by Django 5.2.5 on 2025-08-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
