# Generated by Django 5.2.5 on 2025-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_domaincheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaincheck',
            name='broken_links_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaincheck',
            name='content_size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaincheck',
            name='dns_lookup_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaincheck',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domaincheck',
            name='tls_handshake_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
